from .user_base import UserBase
from .role_base import RoleBase
from .price_base import PriceBase
from .personne_base import PersonneBase
from .item_base import ItemBase
from .stock_base import StockBase
from .stock_line_base import StockLineBase
from .shop_base import ShopBase
from .zip_code_base import ZipCodeBase
from .address_base import AddressBase
from .department_base import DepartmentBase